[versions]
kotlin = "2.0.0"
intellij-plugin = "1.17.4"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij-plugin" }
