[versions]
kotlin = "1.9.23"
intellij-plugin = "1.17.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij-plugin" }
