name: CI

on: push

jobs:
  ci:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      - name: Write some file
        run: |
          pwd
          echo witam > elo.txt